/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#6ddd81",
        "secondary-fixed": "#89fa9b",
        "on-tertiary-fixed-variant": "#783100",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "outline": "#727785",
        "surface-bright": "#fbf9f8",
        "surface-container-high": "#eae8e7",
        "on-tertiary-container": "#0e0200",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#005320",
        "on-surface": "#1b1c1c",
        "tertiary-container": "#c55500",
        "primary-container": "#1a73e8",
        "surface-variant": "#e4e2e1",
        "inverse-on-surface": "#f2f0f0",
        "surface-container-highest": "#e4e2e1",
        "on-secondary": "#ffffff",
        "secondary-container": "#86f898",
        "on-tertiary-fixed": "#341100",
        "on-secondary-fixed": "#002108",
        "inverse-surface": "#303030",
        "on-surface-variant": "#414754",
        "surface-tint": "#005bc0",
        "on-primary-fixed-variant": "#004493",
        "primary-fixed": "#d8e2ff",
        "tertiary-fixed-dim": "#ffb691",
        "on-primary-container": "#ffffff",
        "primary-fixed-dim": "#adc7ff",
        "on-secondary-container": "#00722f",
        "background": "#fbf9f8",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdbcb",
        "surface": "#fbf9f8",
        "inverse-primary": "#adc7ff",
        "secondary": "#006e2c",
        "surface-dim": "#dcd9d9",
        "surface-container": "#f0eded",
        "on-background": "#1b1c1c",
        "on-error": "#ffffff",
        "primary": "#005bbf",
        "tertiary": "#9e4300",
        "surface-container-low": "#f5f3f3",
        "outline-variant": "#c1c6d6",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-primary-fixed": "#001a41"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
